//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 11:31:30 AM AEDT 
//


package employees1_phone;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the employees1_phone package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: employees1_phone
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Employeeversion1 }
     * 
     */
    public Employeeversion1 createEmployeeversion1() {
        return new Employeeversion1();
    }

    /**
     * Create an instance of {@link Employeeversion1 .Employees }
     * 
     */
    public Employeeversion1 .Employees createEmployeeversion1Employees() {
        return new Employeeversion1 .Employees();
    }

    /**
     * Create an instance of {@link Employeeversion1 .Employees.Employee }
     * 
     */
    public Employeeversion1 .Employees.Employee createEmployeeversion1EmployeesEmployee() {
        return new Employeeversion1 .Employees.Employee();
    }

    /**
     * Create an instance of {@link Employeeversion1 .Employees.Employee.Phones }
     * 
     */
    public Employeeversion1 .Employees.Employee.Phones createEmployeeversion1EmployeesEmployeePhones() {
        return new Employeeversion1 .Employees.Employee.Phones();
    }

}
