//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 01:05:08 PM AEDT 
//


package employees1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employees"
})
@XmlRootElement(name = "employeeversion1")
public class Employeeversion1 {

    @XmlElement(required = true)
    protected Employeeversion1 .Employees employees;


    public Employeeversion1 .Employees getEmployees() {
        return employees;
    }


    public void setEmployees(Employeeversion1 .Employees value) {
        this.employees = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employee"
    })
    public static class Employees {

        protected List<Employeeversion1 .Employees.Employee> employee;


        public List<Employeeversion1 .Employees.Employee> getEmployee() {
            if (employee == null) {
                employee = new ArrayList<Employeeversion1 .Employees.Employee>();
            }
            return this.employee;
        }



        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lastname",
            "firstname"
        })
        public static class Employee {

            @XmlElement(required = true)
            protected String lastname;
            @XmlElement(required = true)
            protected String firstname;


            public String getLastname() {
                return lastname;
            }


            public void setLastname(String value) {
                this.lastname = value;
            }


            public String getFirstname() {
                return firstname;
            }


            public void setFirstname(String value) {
                this.firstname = value;
            }

        }

    }

}
