//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 12:19:11 PM AEDT 
//


package employees2withphones;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="staff"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="staffmember" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="givenname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="familyname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="phonenumbers"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="cellphone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="landline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "staff"
})
@XmlRootElement(name = "employeeversion2")
public class Employeeversion2 {

    @XmlElement(required = true)
    protected Employeeversion2 .Staff staff;

    /**
     * Gets the value of the staff property.
     * 
     * @return
     *     possible object is
     *     {@link Employeeversion2 .Staff }
     *     
     */
    public Employeeversion2 .Staff getStaff() {
        return staff;
    }

    /**
     * Sets the value of the staff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeeversion2 .Staff }
     *     
     */
    public void setStaff(Employeeversion2 .Staff value) {
        this.staff = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="staffmember" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="givenname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="familyname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="phonenumbers"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="cellphone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="landline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "staffmember"
    })
    public static class Staff {

        protected List<Employeeversion2 .Staff.Staffmember> staffmember;

        /**
         * Gets the value of the staffmember property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the staffmember property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStaffmember().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Employeeversion2 .Staff.Staffmember }
         * 
         * 
         */
        public List<Employeeversion2 .Staff.Staffmember> getStaffmember() {
            if (staffmember == null) {
                staffmember = new ArrayList<Employeeversion2 .Staff.Staffmember>();
            }
            return this.staffmember;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="givenname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="familyname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="phonenumbers"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="cellphone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="landline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "givenname",
            "familyname",
            "phonenumbers"
        })
        public static class Staffmember {

            @XmlElement(required = true)
            protected String givenname;
            @XmlElement(required = true)
            protected String familyname;
            @XmlElement(required = true)
            protected Employeeversion2 .Staff.Staffmember.Phonenumbers phonenumbers;

            /**
             * Gets the value of the givenname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGivenname() {
                return givenname;
            }

            /**
             * Sets the value of the givenname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGivenname(String value) {
                this.givenname = value;
            }

            /**
             * Gets the value of the familyname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFamilyname() {
                return familyname;
            }

            /**
             * Sets the value of the familyname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFamilyname(String value) {
                this.familyname = value;
            }

            /**
             * Gets the value of the phonenumbers property.
             * 
             * @return
             *     possible object is
             *     {@link Employeeversion2 .Staff.Staffmember.Phonenumbers }
             *     
             */
            public Employeeversion2 .Staff.Staffmember.Phonenumbers getPhonenumbers() {
                return phonenumbers;
            }

            /**
             * Sets the value of the phonenumbers property.
             * 
             * @param value
             *     allowed object is
             *     {@link Employeeversion2 .Staff.Staffmember.Phonenumbers }
             *     
             */
            public void setPhonenumbers(Employeeversion2 .Staff.Staffmember.Phonenumbers value) {
                this.phonenumbers = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="cellphone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="landline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cellphone",
                "landline"
            })
            public static class Phonenumbers {

                @XmlElement(required = true)
                protected String cellphone;
                @XmlElement(required = true)
                protected String landline;

                /**
                 * Gets the value of the cellphone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCellphone() {
                    return cellphone;
                }

                /**
                 * Sets the value of the cellphone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCellphone(String value) {
                    this.cellphone = value;
                }

                /**
                 * Gets the value of the landline property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLandline() {
                    return landline;
                }

                /**
                 * Sets the value of the landline property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLandline(String value) {
                    this.landline = value;
                }

            }

        }

    }

}
