//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 09:31:00 AM AEDT 
//


package employees2phonesaddress;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the employees2phonesaddress package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: employees2phonesaddress
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Employeeversion2 }
     * 
     */
    public Employeeversion2 createEmployeeversion2() {
        return new Employeeversion2();
    }

    /**
     * Create an instance of {@link Employeeversion2 .Staff }
     * 
     */
    public Employeeversion2 .Staff createEmployeeversion2Staff() {
        return new Employeeversion2 .Staff();
    }

    /**
     * Create an instance of {@link Employeeversion2 .Staff.Staffmember }
     * 
     */
    public Employeeversion2 .Staff.Staffmember createEmployeeversion2StaffStaffmember() {
        return new Employeeversion2 .Staff.Staffmember();
    }

    /**
     * Create an instance of {@link Employeeversion2 .Staff.Staffmember.Phonenumbers }
     * 
     */
    public Employeeversion2 .Staff.Staffmember.Phonenumbers createEmployeeversion2StaffStaffmemberPhonenumbers() {
        return new Employeeversion2 .Staff.Staffmember.Phonenumbers();
    }

    /**
     * Create an instance of {@link Employeeversion2 .Staff.Staffmember.Location }
     * 
     */
    public Employeeversion2 .Staff.Staffmember.Location createEmployeeversion2StaffStaffmemberLocation() {
        return new Employeeversion2 .Staff.Staffmember.Location();
    }

}
